# Generated by Django 2.2.28 on 2025-03-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questioncomment',
            old_name='text',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='walkcomment',
            old_name='text',
            new_name='comment',
        ),
    ]
