# Generated by Django 2.2.28 on 2025-03-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stroll', '0002_auto_20250323_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walk',
            name='gallery_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='walk_gelleries/'),
        ),
        migrations.AlterField(
            model_name='walk',
            name='gallery_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='walk_galleries/'),
        ),
        migrations.AlterField(
            model_name='walk',
            name='gallery_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='walk_galleries/'),
        ),
        migrations.AlterField(
            model_name='walk',
            name='gallery_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='walk_galleries/'),
        ),
        migrations.AlterField(
            model_name='walk',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='walk_thumbnails/'),
        ),
    ]
