# Generated by Django 2.2.28 on 2025-03-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stroll', '0002_auto_20250310_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
