# Generated by Django 2.2.28 on 2025-03-22 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stroll', '0002_auto_20250322_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stroll.UserProfile'),
        ),
        migrations.AlterField(
            model_name='walk',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stroll.UserProfile'),
        ),
    ]
