# Generated by Django 2.2.28 on 2025-03-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stroll', '0003_auto_20250323_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
