# Generated by Django 2.2.28 on 2025-03-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stroll', '0004_auto_20250319_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='walk',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='walk',
            name='gallery_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='walk_photos/'),
        ),
        migrations.AlterField(
            model_name='walk',
            name='gallery_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='walk_photos/'),
        ),
        migrations.AlterField(
            model_name='walk',
            name='gallery_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='walk_photos/'),
        ),
        migrations.AlterField(
            model_name='walk',
            name='gallery_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='walk_photos/'),
        ),
        migrations.AlterField(
            model_name='walk',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='walk',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='walk_photos/'),
        ),
    ]
