# Generated by Django 2.2.28 on 2025-03-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stroll', '0005_auto_20250321_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walk',
            name='gallery_image_1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='walk_photos/'),
        ),
        migrations.AlterField(
            model_name='walk',
            name='gallery_image_2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='walk_photos/'),
        ),
        migrations.AlterField(
            model_name='walk',
            name='gallery_image_3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='walk_photos/'),
        ),
        migrations.AlterField(
            model_name='walk',
            name='gallery_image_4',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='walk_photos/'),
        ),
    ]
