# Generated by Django 2.2.28 on 2025-03-23 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stroll', '0005_question_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='slug',
        ),
    ]
