# Generated by Django 2.2.28 on 2025-03-21 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stroll', '0004_auto_20250319_1740'),
        ('stroll', '0005_auto_20250314_1700'),
    ]

    operations = [
    ]
