# Generated by Django 2.2.28 on 2025-03-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stroll', '0006_remove_question_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walk',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='walk_thumbnails/'),
        ),
    ]
