# Generated by Django 2.2.28 on 2025-03-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stroll', '0007_auto_20250322_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='no email', max_length=100),
        ),
    ]
