# Generated by Django 2.2.28 on 2025-03-23 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stroll', '0007_auto_20250322_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'UserProfiles'},
        ),
    ]
