# Generated by Django 2.2.28 on 2025-03-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stroll', '0007_auto_20250324_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walk',
            name='gallery_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='walk_galleries/'),
        ),
    ]
