# Generated by Django 2.2.28 on 2025-03-23 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stroll', '0008_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
