# Generated by Django 2.2.28 on 2025-03-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stroll', '0008_auto_20250321_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
