# Generated by Django 2.2.28 on 2025-03-23 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stroll', '0009_remove_userprofile_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'UserProfiles'},
        ),
    ]
