# Generated by Django 2.2.28 on 2025-03-21 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stroll', '0009_auto_20250321_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walk',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stroll.UserProfile'),
        ),
    ]
