# Generated by Django 2.2.28 on 2025-03-23 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stroll', '0010_auto_20250323_1200'),
        ('stroll', '0008_auto_20250323_1135'),
    ]

    operations = [
    ]
