# Generated by Django 2.2.28 on 2025-03-21 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stroll', '0011_userprofile_is_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walk',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
